package ru.dendevjv.dsalgjavamg.ch03fundamental.exercises;

/**
    R-3.1   (page 145) 
    Give the next five pseudorandom numbers generated by the process described on
    page 113, with a = 12, b = 5, and n = 100, and 92 as the seed for cur.
 */
public class R0301PseudorandomGenerator {
    private static final int DEFAULT_N = 100;
    private static final int DEFAULT_B = 5;
    private static final int DEFAULT_A = 12;
    
    private int current;
    private int a, b, n;
    
    R0301PseudorandomGenerator(int startingCurrent) {
        this(startingCurrent, DEFAULT_A, DEFAULT_B, DEFAULT_N);
    }
    
    R0301PseudorandomGenerator(int startingCurrent, int a, int b, int n) {
        current = startingCurrent;
        this.a = a;
        this.b = b;
        this.n = n;
    }
    
    /**
     * Returns next pseudorandom number.
     */
    int next() {
        int answer = current;
        current = (a * current + b) % n;
        return answer;
    }

    public static void main(String[] args) {
        R0301PseudorandomGenerator gen = new R0301PseudorandomGenerator(92);
        for (int i = 0; i < 35; i++) {
            System.out.println(gen.next());
        }
    }

}
